name: Sync to Secondary Account

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Account B (Excluding Workflows)
        env:
          SEC_TOKEN: ${{ secrets.SECONDARY_ACCOUNT_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

         
          # Commit that deletion locally (check if there are changes to commit first)
          if git diff-index --quiet HEAD --; then
            echo "No changes to workflows to exclude."
          else
            git commit -m "Exclude workflows from sync1"
          fi

          # Add the remote and push
          git remote add second https://${SEC_TOKEN}@github.com/AIBots012/ChatBot.git
          git push second main --force
